package sankarmy;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dell
 */
public class AuthForm extends javax.swing.JFrame{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuthForm.class.getName());

    /**
     * Creates new form AuthForm
     */
    public AuthForm() {
        initComponents();
 // 1. कंप्यूटर की स्क्रीन का असली साइज लें (चाहे कोई भी मॉनिटर हो)
    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    
    // 2. हर स्क्रीन के हिसाब से फुल साइज सेट करें
    this.setSize(screenSize.width, screenSize.height);
    this.setPreferredSize(screenSize);
    this.setMinimumSize(screenSize);
    
    this.setLocationRelativeTo(null);
    centerTheLoginBox();
        // प्रोजेक्ट रन होते ही यह पासवर्ड के स्टार हटाकर हिंट टेक्स्ट दिखा देगा
// 1. यूजरनेम फ़ील्ड के अंदर बाईं तरफ 15 पिक्सेल का स्पेस देने के लिए
txt_login_uname.setMargin(new java.awt.Insets(0, 15, 0, 0));

// 2. पासवर्ड फ़ील्ड के अंदर भी बाईं तरफ 15 पिक्सेल का स्पेस देने के लिए
txt_login_pass.setMargin(new java.awt.Insets(0, 15, 0, 0));

// 3. अगर ऊपर वाला काम न करे, तो यह बॉर्डर पैडिंग कोड डालें (सबसे ताकतवर तरीका)
txt_login_uname.setBorder(javax.swing.BorderFactory.createCompoundBorder(
    txt_login_uname.getBorder(), 
    javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0)
));

txt_login_pass.setBorder(javax.swing.BorderFactory.createCompoundBorder(
    txt_login_pass.getBorder(), 
    javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0)
));
    }
    public void centerTheLoginBox() {
    // 1. जब भी स्क्रीन का साइज बदले, यह कोड रन होगा
    this.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            // पूरे फॉर्म (JFrame) की चौड़ाई और ऊंचाई
            int frameWidth = getContentPane().getWidth();
            int frameHeight = getContentPane().getHeight();
            
            // आपके लॉगिन बॉक्स पैनल की चौड़ाई और ऊंचाई
            int boxWidth = jTabbedPane1.getWidth();
            int boxHeight = jTabbedPane1.getHeight();
            
            // सेंटर की पोजीशन कैलकुलेट करें
            int x = (frameWidth - boxWidth) / 2;
            int y = (frameHeight - boxHeight) / 2;
            
            // लॉगिन बॉक्स को हमेशा सेंटर की पोजीशन पर सेट करें
            jTabbedPane1.setLocation(x, y);
        }
    });
    txt_login_pass.setText("Enter Password");
txt_login_pass.setEchoChar((char) 0); // Disables masking so placeholder text is readable

txt_login_pass.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (String.valueOf(txt_login_pass.getPassword()).equals("Enter Password")) {
            txt_login_pass.setText("");
            txt_login_pass.setEchoChar('*'); // Starts masking when user types password
        }
    }
    @Override
    public void focusLost(java.awt.event.FocusEvent evt) {
        if (String.valueOf(txt_login_pass.getPassword()).isEmpty()) {
            txt_login_pass.setText("Enter Password");
            txt_login_pass.setEchoChar((char) 0); // Stops masking to show hint again
        }
    }
});
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_login_uname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_login_pass = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_fullname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_register = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 204))); // NOI18N
        jTabbedPane1.setForeground(new java.awt.Color(0, 153, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/password-protection.png"))); // NOI18N

        txt_login_uname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_login_uname.setForeground(new java.awt.Color(153, 153, 153));
        txt_login_uname.setText("Enter UserName");
        txt_login_uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_login_uname.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txt_login_uname.setOpaque(true);
        txt_login_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_login_unameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_login_unameFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/account (2).png"))); // NOI18N

        txt_login_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_login_pass.setForeground(new java.awt.Color(153, 153, 153));
        txt_login_pass.setText("Enter Password");
        txt_login_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_login_pass.setMargin(new java.awt.Insets(2, 10, 2, 2));
        txt_login_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_login_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_login_passFocusLost(evt);
            }
        });

        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(0, 153, 51));
        btnlogin.setText("Login");
        btnlogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlogin.addActionListener(this::btnloginActionPerformed);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/login.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/login (1).png"))); // NOI18N
        jLabel8.setText("jLabel8");

        btnExit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(255, 51, 51));
        btnExit1.setText("Exit");
        btnExit1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExit1.addActionListener(this::btnExit1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_login_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_login_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnlogin)
                            .addComponent(btnExit1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Login", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/password-protection.png"))); // NOI18N
        jLabel3.setText("Password");

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/id-card.png"))); // NOI18N
        jLabel4.setText("Full Name");

        txt_fullname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_fullname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/account (2).png"))); // NOI18N
        jLabel5.setText("User Name");

        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(51, 0, 153));
        btn_register.setText("Register");
        btn_register.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_register.addActionListener(this::btn_registerActionPerformed);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/sign-up.gif"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sankarmy/sign-up (1).png"))); // NOI18N

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 51, 51));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_register)
                                .addGap(34, 34, 34)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(txt_fullname)
                                    .addComponent(txt_password))
                                .addGap(206, 206, 206))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_fullname))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_password))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_register)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SignUp", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Sign Up");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
      String fname = txt_fullname.getText();
String uname = txt_username.getText();
String pass = String.valueOf(txt_password.getPassword());

// Validation: Check karna ki koi dabba khali toh nahi hai
if(fname.equals("") || uname.equals("") || pass.equals("")) {
    javax.swing.JOptionPane.showMessageDialog(null, "Kripya sabhi fields ko bharein!");
    return;
}

// Database me data insert karne ki query
String query = "INSERT INTO users (fullname, username, password) VALUES (?, ?, ?)";

try {
    java.sql.Connection con = MyConnection.getConnection();
    if(con != null) {
        java.sql.PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, fname);
        ps.setString(2, uname);
        ps.setString(3, pass);

        if(ps.executeUpdate() > 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Registration Successful! Ab aap Login kar sakte hain.");
            // Dabbo ko khali karna
            txt_fullname.setText("");
            txt_username.setText("");
            txt_password.setText("");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Database se connection nahi ho paya!");
    }
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(null, "Connection Details Error: " + ex.getMessage());
}  
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        String username = txt_login_uname.getText();
String password = new String(txt_login_pass.getPassword()); // अगर पासवर्ड फील्ड है तो getPassword() इस्तेमाल करें

if (username.isEmpty() || password.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter userName and Password");
    return;
}

try {
    // आपकी बनाई हुई MyConnection क्लास से कनेक्शन लेना
     java.sql.Connection con = MyConnection.getConnection();
    
    // डेटाबेस टेबल और कॉलम के नाम अपने हिसाब से बदल लें (जैसे: users टेबल)
    String query = "SELECT * FROM users WHERE username = ? AND password = ?";
    java.sql.PreparedStatement pst = con.prepareStatement(query);
    pst.setString(1, username);
    pst.setString(2, password);
    
    java.sql.ResultSet rs = pst.executeQuery();
    
    if (rs.next()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Login seaccessfully");
        MainFrom mf=new MainFrom();
        mf.setVisible(true);
        this.dispose();
        // यहाँ आप लॉगिन के बाद खुलने वाला अगला पेज/डैशबोर्ड खोल सकते हैं
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Involid password");
    }
    
    con.close(); // connection banda karana
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txt_login_unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_login_unameFocusLost
         if(txt_login_uname.getText().equals("")){
        txt_login_uname.setText("Enter UserName");
        txt_login_uname.setForeground(java.awt.Color.GRAY); // हिंट के लिए ग्रे कलर
    }
    }//GEN-LAST:event_txt_login_unameFocusLost

    private void txt_login_unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_login_unameFocusGained
       if(txt_login_uname.getText().equals("Enter UserName")){
        txt_login_uname.setText("");
        txt_login_uname.setForeground(java.awt.Color.BLACK); // टाइप करते समय ब्लैक कलर
    }
    }//GEN-LAST:event_txt_login_unameFocusGained

    private void txt_login_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_login_passFocusGained
            String pass = String.valueOf(txt_login_pass.getPassword());
    if(pass.equals("Enter Password")){
        txt_login_pass.setText("");
        txt_login_pass.setEchoChar('•');
        txt_login_pass.setForeground(java.awt.Color.BLACK);
    }
    }//GEN-LAST:event_txt_login_passFocusGained

    private void txt_login_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_login_passFocusLost
         String pass = String.valueOf(txt_login_pass.getPassword());
    if(pass.trim().equals("")){
        txt_login_pass.setText("Enter Password");
        txt_login_pass.setEchoChar((char)0);
        txt_login_pass.setForeground(java.awt.Color.GRAY);
    }
    }//GEN-LAST:event_txt_login_passFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AuthForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JPasswordField txt_login_pass;
    private javax.swing.JTextField txt_login_uname;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
