/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sankarmy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author user
 */
public class ItemWisestock extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ItemWisestock.class.getName());

    /**
     * Creates new form ItemWisestock
     */
    public ItemWisestock() {
        initComponents();
        loadItemsToCombo();
 // 1. कंप्यूटर की स्क्रीन का असली साइज लें (चाहे कोई भी मॉनिटर हो)
    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    
    // 2. हर स्क्रीन के हिसाब से फुल साइज सेट करें
    this.setSize(screenSize.width, screenSize.height);
    this.setPreferredSize(screenSize);
    this.setMinimumSize(screenSize);
    
    this.setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblTotalItem = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        myJTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        ExportToExcel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cmbitem = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        EndDate = new com.toedter.calendar.JDateChooser();
        StartDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Up To:");

        lblTotalItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalItem.setForeground(new java.awt.Color(153, 0, 0));

        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(153, 0, 0));

        btnsearch.setText("Search");
        btnsearch.addActionListener(this::btnsearchActionPerformed);

        myJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty Purchased", "Bill_No", "Bill Date", "Amount", "Total Amount", "Purchase Rate/Unit"
            }
        ));
        jScrollPane1.setViewportView(myJTable);

        jLabel11.setText("Barcode Wise Search:");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 153));
        jButton4.setText("Back");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        ExportToExcel.setForeground(new java.awt.Color(0, 51, 204));
        ExportToExcel.setText("Export To EXcel");
        ExportToExcel.addActionListener(this::ExportToExcelActionPerformed);

        jLabel2.setText("Location Wise:");

        jLabel33.setForeground(new java.awt.Color(0, 51, 204));
        jLabel33.setText("Item Wise Purchase Details:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel1.setText("Item Name:");

        cmbitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("From:");

        EndDate.setDateFormatString("yyyy-MM-dd");
        EndDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        StartDate.setDateFormatString("yyyy-MM-dd");
        StartDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(525, 525, 525)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(lblTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(127, 127, 127)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(145, 145, 145))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbitem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ExportToExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnsearch)
                                .addComponent(jButton4)
                                .addComponent(ExportToExcel)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1564, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
     // 1. UI एलिमेंट्स से वैल्यूज प्राप्त करें
    String selectedItem = cmbitem.getSelectedItem().toString();
    
    // तारीखों को सही फॉर्मेट (yyyy-MM-dd) में बदलने के लिए
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String fromDate = "";
    String toDate = "";
    
    try {
        if (StartDate.getDate() != null) {
            fromDate = sdf.format(StartDate.getDate());
        }
        if (EndDate.getDate() != null) {
            toDate = sdf.format(EndDate.getDate());
        }
    } catch (Exception e) {
        System.out.println("तारीख फॉर्मेट एरर: " + e.getMessage());
    }

    // 2. SQL क्वेरी (आपकी phpMyAdmin टेबल संरचना के अनुसार)
    String sql = "SELECT item_name, quantity, invoice_no, purchase_date, purchase_rate, total_amount "
               + "FROM purchase_history_report "
               + "WHERE item_name = ? AND purchase_date BETWEEN ? AND ?";

    // 3. डेटाबेस कनेक्शन और सर्च लॉजिक
    try {
        // अपने डेटाबेस का कनेक्शन यूआरएल (डेटाबेस नाम: sankar)
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/sankar", "root", "");
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, selectedItem);
        pst.setString(2, fromDate);
        pst.setString(3, toDate);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        // JTable का मॉडल निकालकर पुराना डेटा साफ करें
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) myJTable.getModel();
        model.setRowCount(0); 
        
        // डेटाबेस से डेटा निकालकर टेबल में रो (Rows) जोड़ें
        while (rs.next()) {
            Object[] row = {
                rs.getString("item_name"),       // Index 0: Item
                rs.getInt("quantity"),           // Index 1: Qty Purchased
                rs.getString("invoice_no"),      // Index 2: Bill_No
                rs.getDate("purchase_date"),     // Index 3: Bill Date
                rs.getDouble("total_amount"),    // Index 4: Amount
                rs.getDouble("total_amount"),    // Index 5: Total Amount
                rs.getDouble("purchase_rate")    // Index 6: Purchase Rate/Unit
            };
            model.addRow(row); 
        }
        
        // 4. टोटल कैलकुलेट करने का लॉजिक (लूप)
        int totalQty = 0;
        double totalAmount = 0;

        for (int i = 0; i < myJTable.getRowCount(); i++) {
            // Qty Purchased (Index 1) का जोड़
            totalQty += Integer.parseInt(myJTable.getValueAt(i, 1).toString());
            
            // Amount (Index 4) का जोड़
            totalAmount += Double.parseDouble(myJTable.getValueAt(i, 4).toString());
        }

        // 5. वैल्यूज को नीचे वाले लेबल्स (JLabel) में सेट करें
        lblTotalItem.setText("Total Item Qty: " + totalQty);
        lblTotalAmount.setText("Total Amount: " + totalAmount);
        
        // कनेक्शंस बंद करें
        rs.close();
        pst.close();
        conn.close();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "सर्च और कैलकुलेशन एरर: " + e.getMessage());
    }
    }//GEN-LAST:event_btnsearchActionPerformed

     private void loadItemsToCombo() {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    try {
        // ComboBox को पहले से खाली करें ताकि नाम रिपीट न हों
        cmbitem.removeAllItems();
        
        con = MyConnection.getConnection();
        if (con != null) {
            // अपनी सही टेबल का नाम डालें (अगर टेबल का नाम product है तो product रखें)
            String sql = "SELECT item_name FROM items ORDER BY item_name ASC";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {
                // एक-एक करके सारे आइटम ड्रॉपडाउन में जोड़ना
                cmbitem.addItem(rs.getString("item_name"));
            }
        }
    } catch (Exception e) {
        System.out.println("Error loading items: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (Exception ex) {
            // close error log
        }
    }
     }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        
             
           
    }//GEN-LAST:event_jTextField3KeyReleased

    private void ExportToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportToExcelActionPerformed
if (myJTable.getRowCount() == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "टेबल में एक्सपोर्ट करने के लिए कोई डेटा नहीं है!");
    return;
}

try {
    // 2. नया एक्सेल वर्कबुक और शीट बनाएं
    org.apache.poi.ss.usermodel.Workbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
    org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet("Purchase Report");
    
    // 3. एक्सेल में हेडर रो (Columns के नाम) बनाएं
    org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(0);
    for (int i = 0; i < myJTable.getColumnCount(); i++) {
        org.apache.poi.ss.usermodel.Cell cell = headerRow.createCell(i);
        cell.setCellValue(myJTable.getColumnName(i));
    }
    
    // 4. जे-टेबल का सारा डेटा (Rows और Columns) एक्सेल में ट्रांसफर करें
    for (int r = 0; r < myJTable.getRowCount(); r++) {
        org.apache.poi.ss.usermodel.Row row = sheet.createRow(r + 1);
        for (int c = 0; c < myJTable.getColumnCount(); c++) {
            org.apache.poi.ss.usermodel.Cell cell = row.createCell(c);
            Object value = myJTable.getValueAt(r, c);
            if (value != null) {
                cell.setCellValue(value.toString());
            }
        }
    }
    
    // 5. डायरेक्ट डेस्कटॉप का पाथ निकालें (OneDrive को ध्यान में रखते हुए)
    String userHome = System.getProperty("user.home");
    
    // पहले चेक करेंगे कि क्या वनड्राइव वाला डेस्कटॉप मौजूद है
    String folderPath = userHome + java.io.File.separator + "OneDrive" + java.io.File.separator + "Desktop" + java.io.File.separator + "MyPersonalReports";
    java.io.File directory = new java.io.File(folderPath);
    
    // अगर वनड्राइव वाला डेस्कटॉप नहीं मिलता, तो नॉर्मल डेस्कटॉप का इस्तेमाल करेंगे
    if (!directory.getParentFile().exists()) {
        folderPath = userHome + java.io.File.separator + "Desktop" + java.io.File.separator + "MyPersonalReports";
        directory = new java.io.File(folderPath);
    }
    
    // 6. डेस्कटॉप पर नया पर्सनल फोल्डर बनाएं
    if (!directory.exists()) {
        directory.mkdirs(); 
    }
    
    // 7. फाइल का नाम और पूरा रास्ता (Path) सेट करें
    String filePath = folderPath + java.io.File.separator + "PurchaseReport.xlsx";
    // 8. फाइल को बिना संवाद बॉक्स (Dialog) के सीधे बैकग्राउंड में राइट और क्लोज करें
    try (java.io.FileOutputStream out = new java.io.FileOutputStream(filePath)) {
        workbook.write(out);
        workbook.close();
        
        // सफलता का मैसेज
        javax.swing.JOptionPane.showMessageDialog(this, "file destop 'MyPersonalReports' save file!");
    }
    
} catch (Exception e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}        
    }//GEN-LAST:event_ExportToExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ItemWisestock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser EndDate;
    private javax.swing.JButton ExportToExcel;
    private com.toedter.calendar.JDateChooser StartDate;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox cmbitem;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTotalItem;
    private javax.swing.JTable myJTable;
    // End of variables declaration//GEN-END:variables
}
