/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sankarmy;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author dell
 */
public class MainFrom extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrom.class.getName());

    /**
     * Creates new form MainFrom
     */
    public MainFrom() {
        initComponents();
        jPmaster.setVisible(false);
pbarcodesale.setVisible(false);
jPPurchase.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        btnpurchase = new javax.swing.JButton();
        btnothersale = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pbarcodesale = new javax.swing.JPanel();
        btnSale_invoice = new javax.swing.JButton();
        jPmaster = new javax.swing.JPanel();
        btnNewitem = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPPurchase = new javax.swing.JPanel();
        btnPurchase_invoice = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Master");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4);

        btnpurchase.setBackground(new java.awt.Color(0, 204, 204));
        btnpurchase.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnpurchase.setForeground(new java.awt.Color(255, 255, 255));
        btnpurchase.setText("Purchase/Invotry");
        btnpurchase.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnpurchase.setBorderPainted(false);
        btnpurchase.setOpaque(true);
        btnpurchase.addActionListener(this::btnpurchaseActionPerformed);
        jPanel1.add(btnpurchase);

        btnothersale.setBackground(new java.awt.Color(0, 204, 204));
        btnothersale.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnothersale.setForeground(new java.awt.Color(255, 255, 255));
        btnothersale.setText("Other Sale");
        btnothersale.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnothersale.setBorderPainted(false);
        btnothersale.setOpaque(true);
        btnothersale.addActionListener(this::btnothersaleActionPerformed);
        jPanel1.add(btnothersale);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Acount Details");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.setOpaque(true);
        jPanel1.add(jButton3);

        jButton7.setBackground(new java.awt.Color(0, 204, 204));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Reports");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.setOpaque(true);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Data Back UP");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setBorderPainted(false);
        jButton5.setOpaque(true);
        jPanel1.add(jButton5);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(406, 606));
        jPanel2.setVerifyInputWhenFocusTarget(false);

        pbarcodesale.setBackground(new java.awt.Color(0, 204, 204));
        pbarcodesale.setPreferredSize(new java.awt.Dimension(406, 101));
        pbarcodesale.setVerifyInputWhenFocusTarget(false);

        btnSale_invoice.setBackground(new java.awt.Color(0, 204, 204));
        btnSale_invoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSale_invoice.setForeground(new java.awt.Color(255, 255, 255));
        btnSale_invoice.setText("Barcode sale invoice");
        btnSale_invoice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSale_invoice.setBorderPainted(false);
        btnSale_invoice.setOpaque(true);
        btnSale_invoice.addActionListener(this::btnSale_invoiceActionPerformed);

        javax.swing.GroupLayout pbarcodesaleLayout = new javax.swing.GroupLayout(pbarcodesale);
        pbarcodesale.setLayout(pbarcodesaleLayout);
        pbarcodesaleLayout.setHorizontalGroup(
            pbarcodesaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pbarcodesaleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSale_invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pbarcodesaleLayout.setVerticalGroup(
            pbarcodesaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSale_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPmaster.setBackground(new java.awt.Color(0, 204, 204));
        jPmaster.setPreferredSize(new java.awt.Dimension(406, 101));

        btnNewitem.setBackground(new java.awt.Color(0, 204, 204));
        btnNewitem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNewitem.setForeground(new java.awt.Color(255, 255, 255));
        btnNewitem.setText("New Item Entry");
        btnNewitem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNewitem.setBorderPainted(false);
        btnNewitem.setOpaque(true);
        btnNewitem.setPreferredSize(new java.awt.Dimension(140, 19));
        btnNewitem.addActionListener(this::btnNewitemActionPerformed);

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("New staff");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.setBorderPainted(false);
        jButton6.setOpaque(true);
        jButton6.setPreferredSize(new java.awt.Dimension(140, 19));

        javax.swing.GroupLayout jPmasterLayout = new javax.swing.GroupLayout(jPmaster);
        jPmaster.setLayout(jPmasterLayout);
        jPmasterLayout.setHorizontalGroup(
            jPmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmasterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewitem, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
        );
        jPmasterLayout.setVerticalGroup(
            jPmasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPmasterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewitem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPPurchase.setBackground(new java.awt.Color(0, 204, 204));
        jPPurchase.setPreferredSize(new java.awt.Dimension(406, 101));

        btnPurchase_invoice.setBackground(new java.awt.Color(0, 204, 204));
        btnPurchase_invoice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPurchase_invoice.setForeground(new java.awt.Color(255, 255, 255));
        btnPurchase_invoice.setText("Purchase invoice");
        btnPurchase_invoice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPurchase_invoice.setBorderPainted(false);
        btnPurchase_invoice.setOpaque(true);
        btnPurchase_invoice.setPreferredSize(new java.awt.Dimension(140, 19));
        btnPurchase_invoice.addActionListener(this::btnPurchase_invoiceActionPerformed);

        javax.swing.GroupLayout jPPurchaseLayout = new javax.swing.GroupLayout(jPPurchase);
        jPPurchase.setLayout(jPPurchaseLayout);
        jPPurchaseLayout.setHorizontalGroup(
            jPPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPurchase_invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPPurchaseLayout.setVerticalGroup(
            jPPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPurchase_invoice, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPmaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pbarcodesale, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPmaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbarcodesale, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        btnback.setBackground(new java.awt.Color(0, 204, 204));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnback.addActionListener(this::btnbackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1334, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// मास्टर के बटनों को दिखाने के लिए
jPmaster.setVisible(true);
pbarcodesale.setVisible(false);
jPPurchase.setVisible(false);
// स्क्रीन को अपडेट करने के लिए
jPanel1.revalidate();
jPanel1.repaint();
 setButtonActive(jButton4);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpurchaseActionPerformed
jPmaster.setVisible(false);
pbarcodesale.setVisible(false);
jPPurchase.setVisible(true);
// स्क्रीन को अपडेट करने के लिए
jPanel1.revalidate();
jPanel1.repaint();
setButtonActive(btnpurchase);
    }//GEN-LAST:event_btnpurchaseActionPerformed

    private void btnothersaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnothersaleActionPerformed
 jPmaster.setVisible(false);
pbarcodesale.setVisible(true);
jPPurchase.setVisible(false);
// स्क्रीन को अपडेट करने के लिए
jPanel1.revalidate();
jPanel1.repaint(); 
setButtonActive(btnothersale);
    }//GEN-LAST:event_btnothersaleActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
            // 1. अपने Report फॉर्म का ऑब्जेक्ट (Object) बनाएं
    // मान लेते हैं कि आपके फॉर्म का नाम Report है (जैसा कि ऊपर टैब में दिख रहा है)
    Report reportForm = new Report();
    
    // 2. नए फॉर्म को स्क्रीन पर दिखाने के लिए
    reportForm.setVisible(true);
    }//GEN-LAST:event_jButton7MouseClicked

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        AuthForm Auth=new AuthForm();
        Auth.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnNewitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewitemActionPerformed
        Product productForm=new Product();
        productForm.setVisible(true);
    }//GEN-LAST:event_btnNewitemActionPerformed

    private void btnPurchase_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchase_invoiceActionPerformed
        Purchase PurchaseForm=new Purchase();
        PurchaseForm.setVisible(true);
    }//GEN-LAST:event_btnPurchase_invoiceActionPerformed

    private void btnSale_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSale_invoiceActionPerformed
         Sale saleForm=new Sale();
        saleForm.setVisible(true);
    }//GEN-LAST:event_btnSale_invoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrom().setVisible(true));
    }
    // यह फंक्शन सभी बटन्स का रंग एक साथ मैनेज करेगा
private void setButtonActive(javax.swing.JButton activeButton) {
      // 1. आपके सभी बटन्स की लिस्ट
    javax.swing.JButton[] allButtons = {
        btnothersale, btnpurchase, jButton3, jButton4, 
        jButton5, jButton6, jButton7, btnNewitem, 
        btnSale_invoice, btnPurchase_invoice, btnback
    };
    
    // बटन की पैडिंग/मार्जिन फिक्स करने के लिए इनसेट (Insets)
    java.awt.Insets buttonMargin = new java.awt.Insets(2, 14, 2, 14); // (Top, Left, Bottom, Right)
    
    // 2. लूप चलाकर क्लिक हुए बटन को हाइलाइट करें और बाकी को नॉर्मल करें
    for (javax.swing.JButton btn : allButtons) {
        // बटन की साइज को छोटा होने से रोकने के लिए मार्जिन सेट करें
        btn.setMargin(buttonMargin);
        
        if (btn == activeButton) {
            // जो बटन क्लिक हुआ है उसका रंग (गहरा नीला और सफेद टेक्स्ट)
            btn.setBackground(java.awt.Color.decode("#0056b3")); 
            btn.setForeground(java.awt.Color.WHITE);
        } else {
            // बाकी बटन्स का सामान्य रंग (हल्का नीला और काला टेक्स्ट)
            btn.setBackground(java.awt.Color.decode("#5bc0de")); 
            btn.setForeground(java.awt.Color.BLACK);
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewitem;
    private javax.swing.JButton btnPurchase_invoice;
    private javax.swing.JButton btnSale_invoice;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnothersale;
    private javax.swing.JButton btnpurchase;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPPurchase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPmaster;
    private javax.swing.JPanel pbarcodesale;
    // End of variables declaration//GEN-END:variables
}
