/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sankarmy;

/**
 *
 * @author dell
 */
public class Report extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Report.class.getName());

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        panelStock.setVisible(false);
        panelsale.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkstock = new javax.swing.JCheckBox();
        checksale = new javax.swing.JCheckBox();
        panelStock = new javax.swing.JPanel();
        btnStock1 = new javax.swing.JButton();
        btnStock = new javax.swing.JButton();
        panelsale = new javax.swing.JPanel();
        btnPurchasereport = new javax.swing.JButton();
        btnPurchasereport1 = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Report Details");

        checkstock.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        checkstock.setText("Stock Details Report");
        checkstock.addActionListener(this::checkstockActionPerformed);

        checksale.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        checksale.setText("Sale Report");
        checksale.addActionListener(this::checksaleActionPerformed);

        panelStock.setBackground(new java.awt.Color(255, 255, 255));

        btnStock1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStock1.setForeground(new java.awt.Color(255, 0, 153));
        btnStock1.setText("Purchae Claim Report");

        btnStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStock.setForeground(new java.awt.Color(255, 0, 153));
        btnStock.setText("Stock ");
        btnStock.addActionListener(this::btnStockActionPerformed);

        javax.swing.GroupLayout panelStockLayout = new javax.swing.GroupLayout(panelStock);
        panelStock.setLayout(panelStockLayout);
        panelStockLayout.setHorizontalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnStock1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        panelStockLayout.setVerticalGroup(
            panelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStockLayout.createSequentialGroup()
                .addComponent(btnStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStock1)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        panelsale.setBackground(new java.awt.Color(255, 255, 255));

        btnPurchasereport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPurchasereport.setForeground(new java.awt.Color(255, 0, 153));
        btnPurchasereport.setText("Total Sale Datials");

        btnPurchasereport1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPurchasereport1.setForeground(new java.awt.Color(255, 0, 153));
        btnPurchasereport1.setText("Purchae Claim Report");

        javax.swing.GroupLayout panelsaleLayout = new javax.swing.GroupLayout(panelsale);
        panelsale.setLayout(panelsaleLayout);
        panelsaleLayout.setHorizontalGroup(
            panelsaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelsaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPurchasereport1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addComponent(btnPurchasereport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelsaleLayout.setVerticalGroup(
            panelsaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsaleLayout.createSequentialGroup()
                .addComponent(btnPurchasereport1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPurchasereport)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 0, 0));
        btnback.setText("Back");
        btnback.addActionListener(this::btnbackActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(checkstock)
                        .addGap(72, 72, 72)
                        .addComponent(checksale))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(panelStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(panelsale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkstock)
                    .addComponent(checksale))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelsale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkstockActionPerformed

    // अगर टिक है तो दिखेगा, नहीं तो छुपेगा
    panelStock.setVisible(checkstock.isSelected());
    
    // स्क्रीन को तुरंत अपडेट करने के लिए ये दो लाइनें ज़रूरी हैं
    this.revalidate();
    this.repaint();
    }//GEN-LAST:event_checkstockActionPerformed

    private void checksaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checksaleActionPerformed
  
    // अगर टिक है तो दिखेगा, नहीं तो छुपेगा
    panelsale.setVisible(checksale.isSelected());
    
    // स्क्रीन को तुरंत अपडेट करने के लिए ये दो लाइनें ज़रूरी हैं
    this.revalidate();
    this.repaint();
    }//GEN-LAST:event_checksaleActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
         StockReport stockReportForm=new StockReport();
        stockReportForm.setVisible(true);
    }//GEN-LAST:event_btnStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Report().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPurchasereport;
    private javax.swing.JButton btnPurchasereport1;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnStock1;
    private javax.swing.JButton btnback;
    private javax.swing.JCheckBox checksale;
    private javax.swing.JCheckBox checkstock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel panelsale;
    // End of variables declaration//GEN-END:variables
}
