
package sankarmy;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class StockReport extends javax.swing.JFrame {
    java.sql.Connection con = MyConnection.getConnection();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StockReport.class.getName());

    /**
     * Creates new form StockReport
     */
    public StockReport() {
        initComponents();
         loadDefaultStockReport();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    // इस मेथड को Constructor में initComponents(); के बाद कॉल करें
private void loadDefaultStockReport() {
    try {
        // 1. आज की तारीख (Current Date) निकालना
        java.util.Calendar cal = java.util.Calendar.getInstance();
        java.util.Date today = cal.getTime();
        
        // 2. पिछले महीने की आज की तारीख (1 Month Ago) निकालना
        cal.add(java.util.Calendar.MONTH, -1);
        java.util.Date oneMonthAgo = cal.getTime();
        
        // 3. JDateChooser में तारीखें सेट करना
        startdate.setDate(oneMonthAgo);
        enddate.setDate(today);
        
        // 4. डेटाबेस फॉर्मेट में बदलना
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String strFrom = sdf.format(oneMonthAgo);
        String strTo = sdf.format(today);
        
        // 5. SQL क्वेरी चलाना और टेबल में डेटा भरना
        String sql = "SELECT item_id, item_name, purchase_rate, sale_rate, opening_stock, "
                   + "purchase_stock, sale_stock, available_stock "
                   + "FROM stock_report "
                   + "WHERE DATE(last_updated) BETWEEN ? AND ?";
                   
        if (con == null) {
            // con = MyConnection.getConnection(); // अपने कनेक्शन के हिसाब से बदलें
        }
        
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, strFrom);
        pst.setString(2, strTo);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        // Table को साफ़ करके नया डेटा डालना
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) StockTable.getModel();
        model.setRowCount(0); 
        
        while(rs.next()) {
            model.addRow(new Object[]{
                rs.getString("item_id"),
                rs.getString("item_name"),
                rs.getString("purchase_rate"),
                rs.getString("sale_rate"),
                rs.getString("opening_stock"),
                rs.getString("purchase_stock"),
                rs.getString("sale_stock"),
                rs.getString("available_stock")
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "डिफ़ॉल्ट डेटा लोड एरर: " + e.getMessage());
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StockTable = new javax.swing.JTable();
        startdate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enddate = new com.toedter.calendar.JDateChooser();
        btnSearch = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Export_To_PDF = new javax.swing.JButton();
        btnExportToExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        StockTable.setBackground(new java.awt.Color(242, 242, 242));
        StockTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        StockTable.setForeground(new java.awt.Color(255, 51, 51));
        StockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item id", "Item Name", "purchase_rate", "sale_rate", "opening_stock", "purchase_stock", "sale_stock", "available_stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockTable.setShowGrid(true);
        StockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StockTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1293;
        gridBagConstraints.ipady = 505;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 6, 29);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        startdate.setDateFormatString("yyyy-MM-dd");
        startdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 12, 0, 0);
        jPanel1.add(startdate, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 16, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("TO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 18, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        enddate.setDateFormatString("yyyy-MM-dd");
        enddate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 132;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 33, 0, 0);
        jPanel1.add(enddate, gridBagConstraints);

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(204, 0, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 0, 0);
        jPanel1.add(btnSearch, gridBagConstraints);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanel1.add(btnBack, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Stock Report");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        Export_To_PDF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Export_To_PDF.setForeground(new java.awt.Color(204, 0, 0));
        Export_To_PDF.setText("Export To pdf");
        Export_To_PDF.addActionListener(this::Export_To_PDFActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 44, 0, 0);
        jPanel1.add(Export_To_PDF, gridBagConstraints);

        btnExportToExcel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExportToExcel.setForeground(new java.awt.Color(204, 0, 0));
        btnExportToExcel.setText("Export To Excel");
        btnExportToExcel.addActionListener(this::btnExportToExcelActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 0, 0);
        jPanel1.add(btnExportToExcel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockTableMouseClicked

    }//GEN-LAST:event_StockTableMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
   try {
        // 2. चेक करना कि दोनों JDateChooser में तारीख चुनी गई है या नहीं
        if (startdate.getDate() == null || enddate.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "कृपया From और To दोनों तारीखें चुनें!");
            return;
        }

        // 3. तारीख को डेटाबेस के फॉर्मेट 'YYYY-MM-DD' में बदलना
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String strFrom = sdf.format(startdate.getDate());
        String strTo = sdf.format(enddate.getDate());

        // 4. SQL क्वेरी - stock_report टेबल से डेट रेंज फिल्टर करना
        String sql = "SELECT item_id, item_name, purchase_rate, sale_rate, opening_stock, "
                   + "purchase_stock, sale_stock, available_stock "
                   + "FROM stock_report "
                   + "WHERE DATE(last_updated) BETWEEN ? AND ?";

        // 5. डेटाबेस कनेक्शन की जांच और स्टेटमेंट्स तैयार करना
        // नोट: अगर आपकी क्लास में कनेक्शन का नाम 'conn' या 'connection' है, तो नीचे 'con' की जगह उसे लिखें
        if (con == null) {
            // यदि कनेक्शन ग्लोबल डिक्लेयर नहीं है, तो अपनी कनेक्शन क्लास से इसे यहाँ प्राप्त करें:
            // con = MyConnection.getConnection(); 
        }

        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, strFrom);
        pst.setString(2, strTo);
        
        // 6. क्वेरी रन करना और रिजल्ट स्टोर करना
        java.sql.ResultSet rs = pst.executeQuery();
        
        // 7. jTable1 के अंदर डेटा लोड करना (rs2xml.jar की मदद से)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) StockTable.getModel();
model.setRowCount(0); // पुरानी खोजी गई एंट्रीज को साफ करने के लिए

while(rs.next()) {
    model.addRow(new Object[]{
        rs.getString("item_id"),
        rs.getString("item_name"),
        rs.getString("purchase_rate"),
        rs.getString("sale_rate"),
        rs.getString("opening_stock"),
        rs.getString("purchase_stock"),
        rs.getString("sale_stock"),
        rs.getString("available_stock")
    });
}
    } catch (Exception e) {
        // किसी भी प्रकार की एरर आने पर मैसेज बॉक्स दिखाना
        javax.swing.JOptionPane.showMessageDialog(this, "सर्च एरर: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void Export_To_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Export_To_PDFActionPerformed
        // 1. सबसे पहले चेक करें कि आपकी जे-टेबल (jTable1) में डेटा है या नहीं
if (StockTable.getRowCount() == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "table me koi data nehi he");
    return;
}

try {
    // 2. डायरेक्ट डेस्कटॉप (Desktop) का पाथ निकालें (OneDrive को ध्यान में रखते हुए)
    String userHome = System.getProperty("user.home");
    String folderPath = userHome + java.io.File.separator + "OneDrive" + java.io.File.separator + "Desktop" + java.io.File.separator + "MyPersonalReports";
    java.io.File directory = new java.io.File(folderPath);
    
    // अगर वनड्राइव वाला डेस्कटॉप नहीं मिलता, तो नॉर्मल डेस्कटॉप का इस्तेमाल करेंगे
    if (!directory.getParentFile().exists()) {
        folderPath = userHome + java.io.File.separator + "Desktop" + java.io.File.separator + "MyPersonalReports";
        directory = new java.io.File(folderPath);
    }
    
    // अगर फोल्डर डेस्कटॉप पर नहीं बना है, तो कोड उसे अपने आप बना देगा
    if (!directory.exists()) {
        directory.mkdirs(); 
    }
    
    // PDF फाइल का पूरा नाम और रास्ता (Path) सेट करें
    String filePath = folderPath + java.io.File.separator + "StockReport.pdf";

    // 3. iText 9+ के मुख्य ऑब्जेक्ट्स सेटअप करें
    com.itextpdf.kernel.pdf.PdfWriter writer = new com.itextpdf.kernel.pdf.PdfWriter(filePath);
    com.itextpdf.kernel.pdf.PdfDocument pdfDoc = new com.itextpdf.kernel.pdf.PdfDocument(writer);
    com.itextpdf.layout.Document document = new com.itextpdf.layout.Document(pdfDoc);

    // 4. iText 9 के अनुसार सिंपल और एरर-फ्री हेडिंग बनाएं
    com.itextpdf.layout.element.Paragraph heading = new com.itextpdf.layout.element.Paragraph("Stock Report");
    heading.setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER);
    document.add(heading);
    
    // थोड़ा स्पेस देने के लिए खाली पैराग्राफ
    document.add(new com.itextpdf.layout.element.Paragraph("\n"));

    // 5. टेबल के कॉलम्स की संख्या के हिसाब से iText टेबल सेटअप करें
    int totalColumns = StockTable.getColumnCount();
    com.itextpdf.layout.element.Table pdfTable = new com.itextpdf.layout.element.Table(totalColumns);

    // 6. PDF टेबल में हेडर (Columns के नाम) जोड़ें
    for (int i = 0; i < totalColumns; i++) {
        com.itextpdf.layout.element.Cell cell = new com.itextpdf.layout.element.Cell();
        cell.add(new com.itextpdf.layout.element.Paragraph(StockTable.getColumnName(i)));
        pdfTable.addHeaderCell(cell);
    }

    // 7. jTable1 का सारा डेटा (Rows और Columns) PDF टेबल में ट्रांसफर करें
    for (int r = 0; r < StockTable.getRowCount(); r++) {
        for (int c = 0; c < totalColumns; c++) {
            Object value = StockTable.getValueAt(r, c);
            String cellValue = (value != null) ? value.toString() : "";
            pdfTable.addCell(new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(cellValue)));
        }
    }

    // 8. टेबल को डॉक्यूमेंट में जोड़ें और फाइल बंद करें
    document.add(pdfTable);
    document.close();
    javax.swing.JOptionPane.showMessageDialog(this, "PDF save");
    // सफलता का मैसेज
   } catch (Exception e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    
    }//GEN-LAST:event_Export_To_PDFActionPerformed

    

    private void btnExportToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportToExcelActionPerformed
      // 1. सबसे पहले चेक करें कि आपकी जे-टेबल (jTable1) में डेटा है या नहीं
if (StockTable.getRowCount() == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "टेबल में एक्सपोर्ट करने के लिए कोई डेटा नहीं है!");
    return;
}

try {
    // 2. नया एक्सेल वर्कबुक और शीट बनाएं
    org.apache.poi.ss.usermodel.Workbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
    org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet("Stock Report");
    
    // 3. एक्सेल में हेडर रो (Columns के नाम) बनाएं
    org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(0);
    for (int i = 0; i < StockTable.getColumnCount(); i++) {
        org.apache.poi.ss.usermodel.Cell cell = headerRow.createCell(i);
        cell.setCellValue(StockTable.getColumnName(i));
    }
    
    // 4. जे-टेबल का सारा डेटा (Rows और Columns) एक्सेल में ट्रांसफर करें
    for (int r = 0; r < StockTable.getRowCount(); r++) {
        org.apache.poi.ss.usermodel.Row row = sheet.createRow(r + 1);
        for (int c = 0; c < StockTable.getColumnCount(); c++) {
            org.apache.poi.ss.usermodel.Cell cell = row.createCell(c);
            Object value = StockTable.getValueAt(r, c);
            if (value != null) {
                cell.setCellValue(value.toString());
            }
        }
    }
    
    // 5. डायरेक्ट डेस्कटॉप का पाथ निकालें (OneDrive को ध्यान में रखते हुए)
    String userHome = System.getProperty("user.home");
    
    // पहले चेक करेंगे कि क्या वनड्राइव वाला डेस्कटॉप मौजूद है
    String folderPath = userHome + java.io.File.separator + "OneDrive" + java.io.File.separator + "Desktop" + java.io.File.separator + "MyPersonalReports";
    java.io.File directory = new java.io.File(folderPath);
    
    // अगर वनड्राइव वाला डेस्कटॉप नहीं मिलता, तो नॉर्मल डेस्कटॉप का इस्तेमाल करेंगे
    if (!directory.getParentFile().exists()) {
        folderPath = userHome + java.io.File.separator + "Desktop" + java.io.File.separator + "MyPersonalReports";
        directory = new java.io.File(folderPath);
    }
    
    // 6. डेस्कटॉप पर नया पर्सनल फोल्डर बनाएं
    if (!directory.exists()) {
        directory.mkdirs(); 
    }
    
    // 7. फाइल का नाम और पूरा रास्ता (Path) सेट करें
    String filePath = folderPath + java.io.File.separator + "StockReport.xlsx";
    // 8. फाइल को बिना संवाद बॉक्स (Dialog) के सीधे बैकग्राउंड में राइट और क्लोज करें
    try (java.io.FileOutputStream out = new java.io.FileOutputStream(filePath)) {
        workbook.write(out);
        workbook.close();
        
        // सफलता का मैसेज
        javax.swing.JOptionPane.showMessageDialog(this, "file destop 'MyPersonalReports' save file!");
    }
    
} catch (Exception e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnExportToExcelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        StockTable.setRowHeight(35);
StockTable.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));

// हेडर को लेफ्ट अलाइन (Left Align) करने के लिए
javax.swing.table.DefaultTableCellRenderer headerRenderer = (javax.swing.table.DefaultTableCellRenderer)
    StockTable.getTableHeader().getDefaultRenderer();
headerRenderer.setHorizontalAlignment(javax.swing.JLabel.LEFT);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StockReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Export_To_PDF;
    private javax.swing.JTable StockTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExportToExcel;
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser enddate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser startdate;
    // End of variables declaration//GEN-END:variables
}
